#ddev-generated
services:
  dbgate:
    container_name: ddev-${DDEV_SITENAME}-dbgate
    image: ${DBGATE_DOCKER_IMAGE:-dbgate/dbgate:latest}
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    env_file:
      - .env.dbgate
    environment:
      - VIRTUAL_HOST=dbgate.${DDEV_SITENAME}.${DDEV_TLD}
      - HTTP_EXPOSE=3000:3000
      - HTTPS_EXPOSE=3001:3000
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
